# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 610074b63ce71896e82faacb4778685021855f30eb0e2b80b9655164b9370697169b5eaa5fb5f775d6bfa982650d1b2527164ff653854d9c1bd19193659d3df2

test:
  secret_key_base: afcd691a2912f2fd05019a0f9bb6f7cf66eaf318ab8ece9e3c15c4a8fe00cf53915f145278d1dc66fd3f00fa88dcfcb22b94804496592ed81917a75cfd78e20a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
